Sueldo_b = int(input("Ingrese el sueldo base: "))
Porcent = (Sueldo_b*0.10)
Total_su = (Porcent+Sueldo_b)
print ("El concepto de comisiones por las tres ventas es de: " +str(Porcent))
print ("El total de sueldo base y comisión es de: "+str(Total_su))
