Capital_total=int(input("Ingrese el capital que desea invertir: "))
Rz_p=(Capital_total*0.02)
Tot_al =(Rz_p +Capital_total)
print ("El porcentaje del 2% pasado un mes es de: " +str(Rz_p))
print("El total de dinero al cabo del mes es de: " +str(Tot_al))